services:
  - type: web
    name: flask-certificate
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libcairo2 libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
